version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - ylabonte
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    groups:
      aiohttp-stack:
        patterns:
          - "aiohttp"
          - "yarl"
      dev-tools:
        patterns:
          - "ruff"
          - "mypy"
          - "pre-commit"
          - "pytest*"
          - "aioresponses"
      docs-tools:
        patterns:
          - "mkdocs*"
          - "mkdocstrings*"
