name: Enable auto-merge

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  automerge:
    name: Enable auto-merge
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge (rebase)
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --rebase --auto "$PR_URL"
